; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Deli Label Maker"
#define MyAppVersion "2.0"
#define MyAppPublisher "Farmhouse Deli & Pantry LLC"
#define MyAppURL "https://www.thefarmhousedeli.com/"
#define MyAppExeName "main.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{16CD3C3B-6410-4FCB-9785-58360E1581A0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=Deli_Label_Maker_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\makeInstaller\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\Fonts\*"; DestDir: "{app}\Fonts"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\blanks\*"; DestDir: "{app}\blanks"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\labels.db"; DestDir: "{userappdata}\Deli Label Maker"; Flags: ignoreversion
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\Fonts\Albertsthal Typewriter.ttf"; DestDir: "{commonfonts}"; FontInstall: "Albertsthal Typewriter"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\Fonts\LeagueGothic-Regular-VariableFont_wdth.ttf"; DestDir: "{commonfonts}"; FontInstall: "League Gothic Regular"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\Fonts\NimbusSanCon.ttf"; DestDir: "{commonfonts}"; FontInstall: "NimbusSanCon"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "C:\Users\mason\Desktop\deli\Deli-Label-Maker\Fonts\NimbusSanCon Bold.ttf"; DestDir: "{commonfonts}"; FontInstall: "NimbusSanCon Bold"; Flags: onlyifdoesntexist uninsneveruninstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

